# Generated by Django 2.2.1 on 2019-06-04 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(db_index=True, max_length=15, unique=True, verbose_name='Name'),
        ),
    ]
